// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt6crk7QcS9mxK6KMgnT4ywzMe1YPo0dk',
    appId: '1:874233266187:web:a690402089e6cd2f6d870e',
    messagingSenderId: '874233266187',
    projectId: 'utb-bus-app',
    authDomain: 'utb-bus-app.firebaseapp.com',
    storageBucket: 'utb-bus-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDur--F8TS9ppehwyRt8a-0UDDYkvGkB-k',
    appId: '1:874233266187:android:728791be7ba40b426d870e',
    messagingSenderId: '874233266187',
    projectId: 'utb-bus-app',
    storageBucket: 'utb-bus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCqsufH-tlQ4ondEAAPEOA54aNwiU1jE',
    appId: '1:874233266187:ios:908257c87744bdd96d870e',
    messagingSenderId: '874233266187',
    projectId: 'utb-bus-app',
    storageBucket: 'utb-bus-app.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCqsufH-tlQ4ondEAAPEOA54aNwiU1jE',
    appId: '1:874233266187:ios:908257c87744bdd96d870e',
    messagingSenderId: '874233266187',
    projectId: 'utb-bus-app',
    storageBucket: 'utb-bus-app.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt6crk7QcS9mxK6KMgnT4ywzMe1YPo0dk',
    appId: '1:874233266187:web:b461580b6f2201d16d870e',
    messagingSenderId: '874233266187',
    projectId: 'utb-bus-app',
    authDomain: 'utb-bus-app.firebaseapp.com',
    storageBucket: 'utb-bus-app.firebasestorage.app',
  );
}
